# This is a basic workflow to help you get started with Actions

name: Main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call_zero:
    uses: ./.github/workflows/zero.yml
  call_build:
    needs: call_zero
    uses: ./.github/workflows/build.yml
  call_test:
    needs: call_build
    uses: ./.github/workflows/test.yml
  call_deploy:
    needs: call_test
    uses: ./.github/workflows/deploy.yml

   
